INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('PENDIENTE');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('EN PROCESO');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('FINALIZADO');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('CANCELADO');